{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/init"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"IdentityVerification"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","externalID":"c:@M@IdentityVerification@objc(cs)LineStyles(im)init"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/identityverification\/linestyles\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles"]]},"sections":[],"kind":"symbol","references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/init":{"title":"init","url":"\/documentation\/identityverification\/linestyles\/init","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineStyles","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","role":"symbol","url":"\/documentation\/identityverification\/linestyles","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/title","value":"LineStyles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/fragments","value":[{"kind":"identifier","text":"LineStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/navigatorTitle","value":[{"text":"LineStyles","kind":"identifier"}]}]}]}