{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/fetchRequest()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/log\/fetchrequest()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchRequest"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSFetchRequest","text":"NSFetchRequest","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSCoreSDK@objc(cs)Log","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","text":"Log"},{"text":">","kind":"text"}]}]}],"metadata":{"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"fetchRequest()","externalID":"s:9TSCoreSDK3LogC12fetchRequestSo07NSFetchE0CyACGyFZ","modules":[{"name":"TSCoreSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchRequest"},{"kind":"text","text":"() -> "},{"text":"NSFetchRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFetchRequest"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSCoreSDK@objc(cs)Log","text":"Log"},{"kind":"text","text":">"}],"extendedModule":"TSCoreSDK"},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/fetchRequest()":{"type":"topic","url":"\/documentation\/tscoresdk\/log\/fetchrequest()","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchRequest"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSFetchRequest","preciseIdentifier":"c:objc(cs)NSFetchRequest"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSCoreSDK@objc(cs)Log","text":"Log"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/fetchRequest()","title":"fetchRequest()","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title","op":"replace","value":"Log"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments","op":"replace","value":[{"kind":"identifier","text":"Log"}]},{"value":[{"kind":"identifier","text":"Log"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}