{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tscoresdk\/log\/initwithentity:insertintomanagedobjectcontext:"]}],"metadata":{"modules":[{"name":"TSCoreSDK"}],"navigatorTitle":[{"text":"initWithEntity:insertIntoManagedObjectContext:","kind":"identifier"}],"externalID":"c:@M@TSCoreSDK@objc(cs)Log(im)initWithEntity:insertIntoManagedObjectContext:","title":"initWithEntity:insertIntoManagedObjectContext:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithEntity:insertIntoManagedObjectContext:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEntity:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSEntityDescription","text":"NSEntityDescription","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"entity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"insertIntoManagedObjectContext:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSManagedObjectContext","text":"NSManagedObjectContext"},{"kind":"text","text":" *) "},{"text":"context","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/initWithEntity:insertIntoManagedObjectContext:"},"sections":[],"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/initWithEntity:insertIntoManagedObjectContext:":{"title":"initWithEntity:insertIntoManagedObjectContext:","role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEntity:insertIntoManagedObjectContext:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/initWithEntity:insertIntoManagedObjectContext:","url":"\/documentation\/tscoresdk\/log\/initwithentity:insertintomanagedobjectcontext:","navigatorTitle":[{"kind":"identifier","text":"initWithEntity:insertIntoManagedObjectContext:"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title","value":"Log"},{"value":[{"text":"Log","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments"},{"op":"replace","value":[{"text":"Log","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}