{"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/t","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@NSManaged","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"t","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"metadata":{"role":"symbol","externalID":"c:@CM@TSCoreSDK@objc(cs)Log(py)t","modules":[{"name":"TSCoreSDK"}],"extendedModule":"TSCoreSDK","title":"t","navigatorTitle":[{"kind":"identifier","text":"t"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"t"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/log\/t"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tscoresdk\/log\/t"]}],"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/t":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/t","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"t","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"t","kind":"identifier"}],"title":"t","kind":"symbol","url":"\/documentation\/tscoresdk\/log\/t","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"t"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"t","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"t","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1t\/title","value":"t","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1t\/fragments","value":[{"text":"t","kind":"identifier"}]},{"op":"replace","value":"Log","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments","value":[{"text":"Log","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle","value":[{"kind":"identifier","text":"Log"}],"op":"replace"}]}]}