{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection\/getsessiontoken(completion:)"]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/getSessionToken(completion:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSessionToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C22SessionTokenCompletiona","text":"SessionTokenCompletion"},{"text":")","kind":"text"}],"roleHeading":"Type Method","symbolKind":"method","title":"getSessionToken(completion:)","modules":[{"name":"AccountProtection"}],"externalID":"s:17AccountProtection09TSAccountB0C15getSessionToken10completionyySSc_tFZ","role":"symbol"},"abstract":[{"text":"Returns current session token","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSessionToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/SessionTokenCompletion","kind":"typeIdentifier","text":"SessionTokenCompletion","preciseIdentifier":"s:17AccountProtection09TSAccountB0C22SessionTokenCompletiona"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/SessionTokenCompletion":{"abstract":[],"kind":"symbol","url":"\/documentation\/accountprotection\/tsaccountprotection\/sessiontokencompletion","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/SessionTokenCompletion","role":"symbol","title":"TSAccountProtection.SessionTokenCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionTokenCompletion"}],"navigatorTitle":[{"text":"SessionTokenCompletion","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/getSessionToken(completion:)":{"abstract":[{"text":"Returns current session token","type":"text"}],"kind":"symbol","url":"\/documentation\/accountprotection\/tsaccountprotection\/getsessiontoken(completion:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/getSessionToken(completion:)","role":"symbol","title":"getSessionToken(completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSessionToken"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17AccountProtection09TSAccountB0C22SessionTokenCompletiona","text":"SessionTokenCompletion","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TSAccountProtection","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TSAccountProtection"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle","value":[{"kind":"identifier","text":"TSAccountProtection"}]}]}]}