{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"baseUrl","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"https:\/\/api.transmitsecurity.io\/\", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSInitSDKConfiguration","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Is your Account Protection server URL (default: “https:\/\/api.transmitsecurity.io”)","type":"text"}]}],"name":"baseUrl"},{"name":"clientId","content":[{"type":"paragraph","inlineContent":[{"text":"Is your AccountProtection client identifier.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Is an opaque identifier of the user in your system."}],"type":"paragraph"}],"name":"userId"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:)"]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"]]},"metadata":{"modules":[{"name":"AccountProtection"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseUrl","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSInitSDKConfiguration","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV"},{"kind":"text","text":"?)"}],"roleHeading":"Type Method","externalID":"s:17AccountProtection09TSAccountB0C10initialize7baseUrl8clientId04userH013configurationySS_S2SSgAA22TSInitSDKConfigurationVSgtFZ","role":"symbol","title":"initialize(baseUrl:clientId:userId:configuration:)"},"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/initialize(baseUrl:clientId:userId:configuration:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"baseUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSInitSDKConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV"},{"kind":"text","text":"?)"}],"url":"\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:)","type":"topic","abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:)","title":"initialize(baseUrl:clientId:userId:configuration:)","role":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSInitSDKConfiguration":{"navigatorTitle":[{"text":"TSInitSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/accountprotection\/tsinitsdkconfiguration","abstract":[{"type":"text","text":"Configuration options object used in SDK initialization."}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSInitSDKConfiguration","kind":"identifier"}],"title":"TSInitSDKConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSAccountProtection","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments","value":[{"kind":"identifier","text":"TSAccountProtection"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle","value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}