{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection\/tslogconfigurable-implementations"]}],"kind":"article","topicSections":[{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/logDestination(_:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/setLogLevel(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"]]},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"TSLogConfigurable Implementations","modules":[{"name":"AccountProtection"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/TSLogConfigurable-Implementations"},"sections":[],"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/setLogLevel(_:)":{"type":"topic","title":"setLogLevel(_:)","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/setLogLevel(_:)","url":"\/documentation\/accountprotection\/tsaccountprotection\/setloglevel(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9TSCoreSDK10TSLogLevelO","text":"TSLogLevel"},{"text":")","kind":"text"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/logDestination(_:)":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/logDestination(_:)","abstract":[],"title":"logDestination(_:)","url":"\/documentation\/accountprotection\/tsaccountprotection\/logdestination(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logDestination"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TSLoggerDestination","preciseIdentifier":"s:9TSCoreSDK19TSLoggerDestinationO"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TSAccountProtection","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments","op":"replace","value":[{"kind":"identifier","text":"TSAccountProtection"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TSAccountProtection"}]}]}]}