{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/linestyles\/fontstyle"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"FontProperties.fontStyle","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles"]]},"metadata":{"externalID":"s:20IdentityVerification10LineStylesC9fontStyleAA04FontF0Ovp","modules":[{"name":"IdentityVerification"}],"role":"symbol","title":"fontStyle","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:20IdentityVerification9FontStyleO","text":"FontStyle"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:20IdentityVerification9FontStyleO","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","kind":"typeIdentifier","text":"FontStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontStyle","interfaceLanguage":"swift"},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/fontStyle":{"role":"symbol","title":"fontStyle","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontStyle","kind":"symbol","url":"\/documentation\/identityverification\/linestyles\/fontstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO"}],"type":"topic","abstract":[]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineStyles","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","role":"symbol","url":"\/documentation\/identityverification\/linestyles","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontStyle":{"url":"\/documentation\/identityverification\/fontstyle","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FontStyle","kind":"identifier"}],"kind":"symbol","title":"FontStyle","abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","navigatorTitle":[{"kind":"identifier","text":"FontStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/title","value":"LineStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/fragments","value":[{"kind":"identifier","text":"LineStyles"}]},{"op":"replace","value":[{"text":"LineStyles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/navigatorTitle"}]}]}