{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"FontProperties.fontSize","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fontSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/basicstyles\/fontsize"]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontSize","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"fontSize","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fontSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"symbolKind":"property","externalID":"s:20IdentityVerification11BasicStylesC8fontSize14CoreFoundation7CGFloatVvp","modules":[{"name":"IdentityVerification"}]},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles"]]},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/fontSize":{"title":"fontSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontSize"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/identityverification\/basicstyles\/fontsize","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontSize"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title","value":"BasicStyles"},{"value":[{"kind":"identifier","text":"BasicStyles"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle","value":[{"kind":"identifier","text":"BasicStyles"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}