{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"challengeCode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"verifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"challengeCode(verifier:)","externalID":"s:9TSCoreSDK15TSSecurityUtilsC13challengeCode8verifierSSSgAF_tFZ","role":"symbol","roleHeading":"Type Method","modules":[{"name":"TSCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"challengeCode","kind":"identifier"},{"kind":"text","text":"("},{"text":"verifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/challengeCode(verifier:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/tscoresdk\/tssecurityutils\/challengecode(verifier:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/challengeCode(verifier:)":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/challengeCode(verifier:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"verifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"title":"challengeCode(verifier:)","url":"\/documentation\/tscoresdk\/tssecurityutils\/challengecode(verifier:)"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TSSecurityUtils","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments","value":[{"text":"TSSecurityUtils","kind":"identifier"}]},{"op":"replace","value":[{"text":"TSSecurityUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle"}]}]}