{"metadata":{"roleHeading":"Type Method","externalID":"s:9TSCoreSDK15TSSecurityUtilsC25randomBase64EncodedString6lengthSSSgSi_tFZ","modules":[{"name":"TSCoreSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"randomBase64EncodedString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"length"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"randomBase64EncodedString(length:)","role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/tssecurityutils\/randombase64encodedstring(length:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"randomBase64EncodedString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"length"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils"]]},"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomBase64EncodedString(length:)","interfaceLanguage":"swift"},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/randomBase64EncodedString(length:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"randomBase64EncodedString","kind":"identifier"},{"kind":"text","text":"("},{"text":"length","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomBase64EncodedString(length:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/tscoresdk\/tssecurityutils\/randombase64encodedstring(length:)","title":"randomBase64EncodedString(length:)"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title","value":"TSSecurityUtils","op":"replace"},{"value":[{"text":"TSSecurityUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TSSecurityUtils"}]}]}]}