{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection"},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Introduction","level":2,"text":"Introduction","type":"heading"},{"inlineContent":[{"text":"The Account Protection SDK is an iOS client SDK that collects and submits telemetry data to Transmit Security. When initialized, the client SDK will automatically track and submit information of the user journey using various events, device data and user interaction. Once specific user actions are performed on the client side (such as login), the SDK should be called in order to track those action events. The data collected by the SDK can then be queried for recommendations using  ","type":"text"},{"type":"reference","identifier":"https:\/\/developer.transmitsecurity.com\/openapi\/risk\/recommendations\/","isActive":true},{"type":"text","text":"  backend API. Learn more about our  "},{"identifier":"https:\/\/developer.transmitsecurity.com\/guides\/risk\/account_protection_overview\/","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/FridaDetector","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/JWTDecoder","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/RawPointerConvertible","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValueDefining","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValuesProviding"],"generated":true,"title":"Protocols","anchor":"Protocols"},{"anchor":"Structures","title":"Structures","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValueDefinition","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValuesProvider","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSActionEventOptions","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSDrsConfiguration","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTransactionData","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTriggerActionError","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTriggerActionResponse","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TransmitSecurityTriggerActionResponse"]},{"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/BiometryType","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlError","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtectionError","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSProtectionError","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TransmitSecurityAccountProtectionError"],"generated":true,"anchor":"Enumerations","title":"Enumerations"},{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/Swift"],"title":"Extended Modules","anchor":"Extended-Modules"}],"kind":"symbol","metadata":{"roleHeading":"Framework","modules":[{"name":"AccountProtection"}],"externalID":"AccountProtection","symbolKind":"module","title":"AccountProtection","role":"collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection"]},{"paths":["\/documentation\/accountprotection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/Swift":{"url":"\/documentation\/accountprotection\/swift","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/Swift","title":"Swift","abstract":[]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSInitSDKConfiguration":{"navigatorTitle":[{"text":"TSInitSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/accountprotection\/tsinitsdkconfiguration","abstract":[{"type":"text","text":"Configuration options object used in SDK initialization."}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSInitSDKConfiguration","kind":"identifier"}],"title":"TSInitSDKConfiguration"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/FridaDetector":{"type":"topic","abstract":[],"title":"FridaDetector","url":"\/documentation\/accountprotection\/fridadetector","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/FridaDetector","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FridaDetector","kind":"identifier"}],"navigatorTitle":[{"text":"FridaDetector","kind":"identifier"}],"role":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/AccountProtectionVersionString":{"title":"AccountProtectionVersionString","type":"topic","url":"\/documentation\/accountprotection\/accountprotectionversionstring","role":"symbol","fragments":[{"text":"AccountProtectionVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/AccountProtectionVersionString","abstract":[{"text":"Project version string for AccountProtection.","type":"text"}],"kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSDrsConfiguration":{"type":"topic","title":"TSDrsConfiguration","abstract":[{"text":"Additional configuration for SDK initialization.","type":"text"}],"role":"symbol","url":"\/documentation\/accountprotection\/tsdrsconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TSDrsConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSDrsConfiguration","navigatorTitle":[{"text":"TSDrsConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/JWTDecoder":{"title":"JWTDecoder","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/JWTDecoder","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWTDecoder"}],"role":"symbol","navigatorTitle":[{"text":"JWTDecoder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/accountprotection\/jwtdecoder"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSTriggerActionResponse":{"kind":"symbol","role":"symbol","title":"TSTriggerActionResponse","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSTriggerActionResponse","kind":"identifier"}],"url":"\/documentation\/accountprotection\/tstriggeractionresponse","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTriggerActionResponse","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSTriggerActionResponse"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TransmitSecurityTriggerActionResponse":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TransmitSecurityTriggerActionResponse","type":"topic","url":"\/documentation\/accountprotection\/transmitsecuritytriggeractionresponse","role":"symbol","title":"TransmitSecurityTriggerActionResponse","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TransmitSecurityTriggerActionResponse","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"TransmitSecurityTriggerActionResponse","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSTransactionData":{"type":"topic","role":"symbol","title":"TSTransactionData","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTransactionData","url":"\/documentation\/accountprotection\/tstransactiondata","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSTransactionData"}],"navigatorTitle":[{"text":"TSTransactionData","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/AccountProtectionVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for AccountProtection."}],"fragments":[{"text":"AccountProtectionVersionNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/AccountProtectionVersionNumber","role":"symbol","url":"\/documentation\/accountprotection\/accountprotectionversionnumber","title":"AccountProtectionVersionNumber"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/SystemControlValueDefining":{"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValueDefining","title":"SystemControlValueDefining","kind":"symbol","role":"symbol","url":"\/documentation\/accountprotection\/systemcontrolvaluedefining","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SystemControlValueDefining","kind":"identifier"}],"navigatorTitle":[{"text":"SystemControlValueDefining","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/BiometryType":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"BiometryType"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/BiometryType","title":"BiometryType","kind":"symbol","url":"\/documentation\/accountprotection\/biometrytype","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BiometryType"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSProtectionError":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSProtectionError"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSProtectionError"}],"url":"\/documentation\/accountprotection\/tsprotectionerror","type":"topic","role":"symbol","title":"TSProtectionError","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSProtectionError"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TransmitSecurityAccountProtectionError":{"url":"\/documentation\/accountprotection\/transmitsecurityaccountprotectionerror","navigatorTitle":[{"text":"TransmitSecurityAccountProtectionError","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TransmitSecurityAccountProtectionError","abstract":[],"title":"TransmitSecurityAccountProtectionError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransmitSecurityAccountProtectionError"}],"kind":"symbol"},"https://developer.transmitsecurity.com/openapi/risk/recommendations/":{"titleInlineContent":[{"type":"text","text":"Recommendations"}],"url":"https:\/\/developer.transmitsecurity.com\/openapi\/risk\/recommendations\/","title":"Recommendations","type":"link","identifier":"https:\/\/developer.transmitsecurity.com\/openapi\/risk\/recommendations\/"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/SystemControlValueDefinition":{"navigatorTitle":[{"text":"SystemControlValueDefinition","kind":"identifier"}],"title":"SystemControlValueDefinition","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SystemControlValueDefinition","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValueDefinition","url":"\/documentation\/accountprotection\/systemcontrolvaluedefinition","kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/SystemControlError":{"abstract":[],"role":"symbol","title":"SystemControlError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SystemControlError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SystemControlError"}],"kind":"symbol","url":"\/documentation\/accountprotection\/systemcontrolerror","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlError","type":"topic"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/SystemControlValuesProviding":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemControlValuesProviding"}],"role":"symbol","title":"SystemControlValuesProviding","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValuesProviding","url":"\/documentation\/accountprotection\/systemcontrolvaluesproviding","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SystemControlValuesProviding"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/SystemControlValuesProvider":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/SystemControlValuesProvider","abstract":[],"url":"\/documentation\/accountprotection\/systemcontrolvaluesprovider","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SystemControlValuesProvider"}],"title":"SystemControlValuesProvider","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemControlValuesProvider"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtectionError":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TSAccountProtectionError","kind":"identifier"}],"title":"TSAccountProtectionError","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtectionError","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSAccountProtectionError","kind":"identifier"}],"url":"\/documentation\/accountprotection\/tsaccountprotectionerror"},"https://developer.transmitsecurity.com/guides/risk/account_protection_overview/":{"titleInlineContent":[{"text":"account protection","type":"text"}],"url":"https:\/\/developer.transmitsecurity.com\/guides\/risk\/account_protection_overview\/","title":"account protection","type":"link","identifier":"https:\/\/developer.transmitsecurity.com\/guides\/risk\/account_protection_overview\/"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/RawPointerConvertible":{"url":"\/documentation\/accountprotection\/rawpointerconvertible","navigatorTitle":[{"kind":"identifier","text":"RawPointerConvertible"}],"kind":"symbol","title":"RawPointerConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawPointerConvertible"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/RawPointerConvertible","type":"topic","role":"symbol","abstract":[]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSActionEventOptions":{"title":"TSActionEventOptions","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSActionEventOptions","navigatorTitle":[{"kind":"identifier","text":"TSActionEventOptions"}],"url":"\/documentation\/accountprotection\/tsactioneventoptions","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSActionEventOptions"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSTriggerActionError":{"url":"\/documentation\/accountprotection\/tstriggeractionerror","role":"symbol","title":"TSTriggerActionError","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSTriggerActionError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSTriggerActionError"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSTriggerActionError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"],"generated":true},{"generated":true,"title":"Variables","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/AccountProtectionVersionNumber","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/AccountProtectionVersionString"],"anchor":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"TSAccountProtection","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TSAccountProtection"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle"}]}]}