{"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/start(startToken:)","interfaceLanguage":"swift"},"abstract":[{"text":"Initiates the verification process for the user and guides them through the entire identity verification flow using the Transmit experience.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"externalID":"s:20IdentityVerification010TSIdentityB0C5start0D5TokenySS_tFZ","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"IdentityVerification"}],"role":"symbol","title":"start(startToken:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"startToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The start_token returned upon session creation, used to bind the session to the device"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/tsidentityverification\/start(starttoken:)"]}],"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/start(startToken:)":{"role":"symbol","kind":"symbol","title":"start(startToken:)","url":"\/documentation\/identityverification\/tsidentityverification\/start(starttoken:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"startToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initiates the verification process for the user and guides them through the entire identity verification flow using the Transmit experience."}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/start(startToken:)","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","value":"TSIdentityVerification"},{"value":[{"text":"TSIdentityVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","value":[{"text":"TSIdentityVerification","kind":"identifier"}]}]}]}