{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startFaceAuth(deviceSessionId:)"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startFaceAuth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceSessionId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device_session_id is a persistent identifier of current session authentication process."}]}],"name":"deviceSessionId"}]}],"abstract":[{"text":"Initiates the face authentication process for the user and guides them through the entire face authentication flow using the Transmit experience.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startFaceAuth","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceSessionId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"startFaceAuth(deviceSessionId:)","symbolKind":"method","externalID":"s:20IdentityVerification010TSIdentityB0C13startFaceAuth15deviceSessionIdySS_tFZ","role":"symbol","roleHeading":"Type Method","modules":[{"name":"IdentityVerification"}]},"variants":[{"paths":["\/documentation\/identityverification\/tsidentityverification\/startfaceauth(devicesessionid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/startFaceAuth(deviceSessionId:)":{"url":"\/documentation\/identityverification\/tsidentityverification\/startfaceauth(devicesessionid:)","abstract":[{"type":"text","text":"Initiates the face authentication process for the user and guides them through the entire face authentication flow using the Transmit experience."}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startFaceAuth(deviceSessionId:)","kind":"symbol","title":"startFaceAuth(deviceSessionId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startFaceAuth"},{"text":"(","kind":"text"},{"text":"deviceSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","value":"TSIdentityVerification"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","value":[{"kind":"identifier","text":"TSIdentityVerification"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","value":[{"text":"TSIdentityVerification","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}