{"sections":[],"topicSections":[{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSAESDataEncrypter","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBinding","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionManager","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionServerProvider","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSyncServerController","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSECService","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptServerRequestDataProvider","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSFile","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSKeychain","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLocalAuthentication","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLog","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogger","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkManager","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkRequestConfiguration","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkService","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRSAConverter","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRSAService","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSReachability","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRequestError","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSResponseGenericHeader","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSDKError","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSStorageError","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSUserDefauls","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TS_AES","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/ThreadSafeContainer"]},{"title":"Protocols","anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/ITSModuleInfo","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSBaseNetworkRequest","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingParameters","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingProtocol","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionProtocol","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSource","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSyncServer","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptEventsProviderProtocol","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogConfigurable","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSResponse","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRetriableRequest"]},{"title":"Structures","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/AES256","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/EnctyptedContainer","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/NoReply","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSConstants","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSession","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionConfiguration","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionManagerConfiguration","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSJSONCodingKeys","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLocalAuthContext","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSPublicKeyData"],"anchor":"Structures","generated":true},{"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Parameters","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSClientRequestData","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptedClientRequestData","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSServerResponseData"],"generated":true,"anchor":"Type-Aliases","title":"Type Aliases"},{"generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/KeychainSwiftAccessOptions","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingKeyType","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSHttpMethod","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogLevel","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLoggerDestination","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRequestErrorCode","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRetriableErrorHandler","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSStorageErrorCode"],"title":"Enumerations"},{"title":"Extended Modules","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/CryptoKit","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Foundation","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Swift"],"anchor":"Extended-Modules"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tscoresdk"]}],"kind":"symbol","metadata":{"modules":[{"name":"TSCoreSDK"}],"roleHeading":"Framework","symbolKind":"module","role":"collection","title":"TSCoreSDK","externalID":"TSCoreSDK"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK"},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRSAConverter":{"abstract":[],"url":"\/documentation\/tscoresdk\/tsrsaconverter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSRSAConverter","kind":"identifier"}],"navigatorTitle":[{"text":"TSRSAConverter","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRSAConverter","title":"TSRSAConverter","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/ITSModuleInfo":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/ITSModuleInfo","abstract":[],"navigatorTitle":[{"text":"ITSModuleInfo","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/itsmoduleinfo","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ITSModuleInfo","kind":"identifier"}],"title":"ITSModuleInfo"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLogConfigurable":{"kind":"symbol","abstract":[],"role":"symbol","title":"TSLogConfigurable","navigatorTitle":[{"kind":"identifier","text":"TSLogConfigurable"}],"url":"\/documentation\/tscoresdk\/tslogconfigurable","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSLogConfigurable","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogConfigurable"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSPublicKeyData":{"kind":"symbol","title":"TSPublicKeyData","url":"\/documentation\/tscoresdk\/tspublickeydata","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSPublicKeyData"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSPublicKeyData","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSPublicKeyData"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoException":{"kind":"symbol","title":"TSCryptoException","url":"\/documentation\/tscoresdk\/tscryptoexception","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSCryptoException"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSCryptoException"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRetriableRequest":{"kind":"symbol","url":"\/documentation\/tscoresdk\/tsretriablerequest","role":"symbol","title":"TSRetriableRequest","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSRetriableRequest"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRetriableRequest","abstract":[],"navigatorTitle":[{"text":"TSRetriableRequest","kind":"identifier"}],"type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRSAService":{"type":"topic","navigatorTitle":[{"text":"TSRSAService","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsrsaservice","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSRSAService","kind":"identifier"}],"title":"TSRSAService","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRSAService","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRequestError":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSRequestError","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRequestError","title":"TSRequestError","type":"topic","url":"\/documentation\/tscoresdk\/tsrequesterror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSRequestError"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Foundation":{"title":"Foundation","kind":"symbol","role":"collection","url":"\/documentation\/tscoresdk\/foundation","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Foundation","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSJSONCodingKeys":{"navigatorTitle":[{"text":"TSJSONCodingKeys","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsjsoncodingkeys","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSJSONCodingKeys","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSJSONCodingKeys","kind":"identifier"}],"title":"TSJSONCodingKeys","type":"topic","role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoBindingKeyType":{"title":"TSCryptoBindingKeyType","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TSCryptoBindingKeyType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSCryptoBindingKeyType"}],"url":"\/documentation\/tscoresdk\/tscryptobindingkeytype","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingKeyType","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSNetworkRequestConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSNetworkRequestConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkRequestConfiguration","url":"\/documentation\/tscoresdk\/tsnetworkrequestconfiguration","title":"TSNetworkRequestConfiguration","type":"topic","navigatorTitle":[{"text":"TSNetworkRequestConfiguration","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSNetworkManager":{"title":"TSNetworkManager","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSNetworkManager","kind":"identifier"}],"navigatorTitle":[{"text":"TSNetworkManager","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsnetworkmanager","abstract":[],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkManager"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSAESDataEncrypter":{"url":"\/documentation\/tscoresdk\/tsaesdataencrypter","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSAESDataEncrypter","title":"TSAESDataEncrypter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSAESDataEncrypter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSAESDataEncrypter"}],"abstract":[],"role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/EnctyptedContainer":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnctyptedContainer"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/EnctyptedContainer","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"EnctyptedContainer","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/enctyptedcontainer","title":"EnctyptedContainer"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoBinding":{"title":"TSCryptoBinding","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSCryptoBinding"}],"type":"topic","kind":"symbol","url":"\/documentation\/tscoresdk\/tscryptobinding","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TSCryptoBinding","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBinding"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSessionConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSCryptoSessionConfiguration"}],"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSCryptoSessionConfiguration"}],"kind":"symbol","url":"\/documentation\/tscoresdk\/tscryptosessionconfiguration","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionConfiguration","title":"TSCryptoSessionConfiguration","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLog":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLog","type":"topic","url":"\/documentation\/tscoresdk\/tslog","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSLog","kind":"identifier"}],"title":"TSLog","navigatorTitle":[{"kind":"identifier","text":"TSLog"}],"abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSReachability":{"url":"\/documentation\/tscoresdk\/tsreachability","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TSReachability","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSReachability","kind":"identifier"}],"title":"TSReachability","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSReachability"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSessionManager":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionManager","title":"TSCryptoSessionManager","navigatorTitle":[{"text":"TSCryptoSessionManager","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tscryptosessionmanager","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSCryptoSessionManager","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSDataSource":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSource","role":"symbol","navigatorTitle":[{"text":"TSDataSource","kind":"identifier"}],"title":"TSDataSource","url":"\/documentation\/tscoresdk\/tsdatasource","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSDataSource","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCoreSDKVersionString":{"url":"\/documentation\/tscoresdk\/tscoresdkversionstring","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"TSCoreSDKVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCoreSDKVersionString","abstract":[{"type":"text","text":"Project version string for TSCoreSDK."}],"title":"TSCoreSDKVersionString"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSFile":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSFile","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSFile","type":"topic","title":"TSFile","kind":"symbol","navigatorTitle":[{"text":"TSFile","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsfile"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRetriableErrorHandler":{"navigatorTitle":[{"text":"TSRetriableErrorHandler","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRetriableErrorHandler","type":"topic","title":"TSRetriableErrorHandler","url":"\/documentation\/tscoresdk\/tsretriableerrorhandler","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSRetriableErrorHandler"}],"role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSessionServerProvider":{"navigatorTitle":[{"kind":"identifier","text":"TSCryptoSessionServerProvider"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSCryptoSessionServerProvider"}],"title":"TSCryptoSessionServerProvider","abstract":[],"url":"\/documentation\/tscoresdk\/tscryptosessionserverprovider","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionServerProvider","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSDataSyncServerController":{"url":"\/documentation\/tscoresdk\/tsdatasyncservercontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSDataSyncServerController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSDataSyncServerController"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSyncServerController","title":"TSDataSyncServerController"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSResponseGenericHeader":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSResponseGenericHeader"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSResponseGenericHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSResponseGenericHeader"}],"url":"\/documentation\/tscoresdk\/tsresponsegenericheader","type":"topic","title":"TSResponseGenericHeader","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Swift":{"title":"Swift","url":"\/documentation\/tscoresdk\/swift","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Swift","abstract":[],"type":"topic","role":"collection","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoBindingProtocol":{"navigatorTitle":[{"text":"TSCryptoBindingProtocol","kind":"identifier"}],"type":"topic","url":"\/documentation\/tscoresdk\/tscryptobindingprotocol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TSCryptoBindingProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingProtocol","title":"TSCryptoBindingProtocol","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSStorageErrorCode":{"role":"symbol","navigatorTitle":[{"text":"TSStorageErrorCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSStorageErrorCode"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSStorageErrorCode","url":"\/documentation\/tscoresdk\/tsstorageerrorcode","title":"TSStorageErrorCode","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/ThreadSafeContainer":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThreadSafeContainer","kind":"identifier"}],"type":"topic","url":"\/documentation\/tscoresdk\/threadsafecontainer","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/ThreadSafeContainer","abstract":[],"title":"ThreadSafeContainer","navigatorTitle":[{"text":"ThreadSafeContainer","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoBindingParameters":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TSCryptoBindingParameters","kind":"identifier"}],"navigatorTitle":[{"text":"TSCryptoBindingParameters","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoBindingParameters","url":"\/documentation\/tscoresdk\/tscryptobindingparameters","type":"topic","title":"TSCryptoBindingParameters","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSHttpMethod":{"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSHttpMethod","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSHttpMethod","type":"topic","url":"\/documentation\/tscoresdk\/tshttpmethod","title":"TSHttpMethod","navigatorTitle":[{"text":"TSHttpMethod","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore":{"type":"topic","title":"TSCore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSCore","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tscore","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSCore"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSResponse":{"navigatorTitle":[{"text":"TSResponse","kind":"identifier"}],"title":"TSResponse","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSResponse","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSResponse","url":"\/documentation\/tscoresdk\/tsresponse","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSEncryptedClientRequestData":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSEncryptedClientRequestData"}],"title":"TSEncryptedClientRequestData","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptedClientRequestData","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TSEncryptedClientRequestData","kind":"identifier"}],"abstract":[],"url":"\/documentation\/tscoresdk\/tsencryptedclientrequestdata"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSDKError":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TSSDKError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSDKError","title":"TSSDKError","url":"\/documentation\/tscoresdk\/tssdkerror","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TSSDKError","kind":"identifier"}],"type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSStorageError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSStorageError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSStorageError","title":"TSStorageError","url":"\/documentation\/tscoresdk\/tsstorageerror","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TSStorageError","kind":"identifier"}],"type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSessionManagerConfiguration":{"title":"TSCryptoSessionManagerConfiguration","navigatorTitle":[{"kind":"identifier","text":"TSCryptoSessionManagerConfiguration"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionManagerConfiguration","type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/tscoresdk\/tscryptosessionmanagerconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSCryptoSessionManagerConfiguration","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSKeychain":{"title":"TSKeychain","abstract":[{"type":"text","text":"A collection of helper functions for saving text and data in the keychain."}],"url":"\/documentation\/tscoresdk\/tskeychain","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSKeychain","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSKeychain","kind":"identifier"}],"navigatorTitle":[{"text":"TSKeychain","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLocalAuthentication":{"kind":"symbol","title":"TSLocalAuthentication","role":"symbol","url":"\/documentation\/tscoresdk\/tslocalauthentication","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSLocalAuthentication"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLocalAuthentication","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSLocalAuthentication"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSRequestErrorCode":{"kind":"symbol","abstract":[{"text":"Custom Error enum that we’ll use in case","type":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSRequestErrorCode","role":"symbol","url":"\/documentation\/tscoresdk\/tsrequesterrorcode","title":"TSRequestErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TSRequestErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"TSRequestErrorCode","kind":"identifier"}],"type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLocalAuthContext":{"title":"TSLocalAuthContext","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSLocalAuthContext","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/tscoresdk\/tslocalauthcontext","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TSLocalAuthContext","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLocalAuthContext"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSServerResponseData":{"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSServerResponseData","title":"TSServerResponseData","navigatorTitle":[{"text":"TSServerResponseData","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TSServerResponseData","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsserverresponsedata","role":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Parameters":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Parameters","title":"Parameters","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Parameters"}],"url":"\/documentation\/tscoresdk\/parameters","navigatorTitle":[{"kind":"identifier","text":"Parameters"}],"role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSECService":{"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSECService","type":"topic","url":"\/documentation\/tscoresdk\/tsecservice","kind":"symbol","role":"symbol","title":"TSECService","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSECService"}],"navigatorTitle":[{"kind":"identifier","text":"TSECService"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLogLevel":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogLevel","navigatorTitle":[{"kind":"identifier","text":"TSLogLevel"}],"url":"\/documentation\/tscoresdk\/tsloglevel","title":"TSLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSLogLevel","kind":"identifier"}],"role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSConstants":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSConstants"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSConstants","kind":"identifier"}],"title":"TSConstants","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSConstants","type":"topic","url":"\/documentation\/tscoresdk\/tsconstants"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSEncryptServerRequestDataProvider":{"kind":"symbol","url":"\/documentation\/tscoresdk\/tsencryptserverrequestdataprovider","abstract":[],"title":"TSEncryptServerRequestDataProvider","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptServerRequestDataProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSEncryptServerRequestDataProvider"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"TSEncryptServerRequestDataProvider","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSession":{"title":"TSCryptoSession","role":"symbol","navigatorTitle":[{"text":"TSCryptoSession","kind":"identifier"}],"abstract":[],"url":"\/documentation\/tscoresdk\/tscryptosession","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSession","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSCryptoSession","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLoggerDestination":{"title":"TSLoggerDestination","url":"\/documentation\/tscoresdk\/tsloggerdestination","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLoggerDestination","navigatorTitle":[{"kind":"identifier","text":"TSLoggerDestination"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSLoggerDestination","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSEncryptEventsProviderProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSEncryptEventsProviderProtocol"}],"url":"\/documentation\/tscoresdk\/tsencrypteventsproviderprotocol","navigatorTitle":[{"text":"TSEncryptEventsProviderProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSEncryptEventsProviderProtocol","role":"symbol","kind":"symbol","title":"TSEncryptEventsProviderProtocol","type":"topic","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/CryptoKit":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/CryptoKit","url":"\/documentation\/tscoresdk\/cryptokit","title":"CryptoKit","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/KeychainSwiftAccessOptions":{"navigatorTitle":[{"text":"KeychainSwiftAccessOptions","kind":"identifier"}],"title":"KeychainSwiftAccessOptions","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeychainSwiftAccessOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"These options are used to determine when a keychain item should be readable. The default value is AccessibleWhenUnlocked."}],"url":"\/documentation\/tscoresdk\/keychainswiftaccessoptions","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/KeychainSwiftAccessOptions"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSLogger":{"role":"symbol","abstract":[],"title":"TSLogger","url":"\/documentation\/tscoresdk\/tslogger","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSLogger","kind":"identifier"}],"navigatorTitle":[{"text":"TSLogger","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSLogger"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCoreSDKVersionNumber":{"fragments":[{"kind":"identifier","text":"TSCoreSDKVersionNumber"}],"title":"TSCoreSDKVersionNumber","url":"\/documentation\/tscoresdk\/tscoresdkversionnumber","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCoreSDKVersionNumber","abstract":[{"type":"text","text":"Project version number for TSCoreSDK."}],"role":"symbol","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCryptoSessionProtocol":{"abstract":[],"url":"\/documentation\/tscoresdk\/tscryptosessionprotocol","title":"TSCryptoSessionProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSCryptoSessionProtocol","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TSCryptoSessionProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCryptoSessionProtocol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/AES256":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/AES256","title":"AES256","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AES256"}],"navigatorTitle":[{"kind":"identifier","text":"AES256"}],"url":"\/documentation\/tscoresdk\/aes256","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSUserDefauls":{"abstract":[],"role":"symbol","url":"\/documentation\/tscoresdk\/tsuserdefauls","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSUserDefauls","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSUserDefauls"}],"navigatorTitle":[{"kind":"identifier","text":"TSUserDefauls"}],"title":"TSUserDefauls"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSBaseNetworkRequest":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSBaseNetworkRequest","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TSBaseNetworkRequest","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tsbasenetworkrequest","role":"symbol","type":"topic","navigatorTitle":[{"text":"TSBaseNetworkRequest","kind":"identifier"}],"abstract":[],"title":"TSBaseNetworkRequest"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TS_AES":{"kind":"symbol","title":"TS_AES","url":"\/documentation\/tscoresdk\/ts_aes","abstract":[],"type":"topic","navigatorTitle":[{"text":"TS_AES","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TS_AES","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TS_AES","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/NoReply":{"abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NoReply"}],"url":"\/documentation\/tscoresdk\/noreply","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/NoReply","kind":"symbol","title":"NoReply","navigatorTitle":[{"kind":"identifier","text":"NoReply"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSClientRequestData":{"url":"\/documentation\/tscoresdk\/tsclientrequestdata","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSClientRequestData","role":"symbol","title":"TSClientRequestData","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSClientRequestData"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSClientRequestData"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSNetworkService":{"url":"\/documentation\/tscoresdk\/tsnetworkservice","title":"TSNetworkService","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSNetworkService","navigatorTitle":[{"text":"TSNetworkService","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSNetworkService","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSDataSyncServer":{"navigatorTitle":[{"kind":"identifier","text":"TSDataSyncServer"}],"url":"\/documentation\/tscoresdk\/tsdatasyncserver","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSDataSyncServer"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSDataSyncServer","kind":"symbol","role":"symbol","title":"TSDataSyncServer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils"],"anchor":"Classes"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCoreSDKVersionNumber","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCoreSDKVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title","value":"TSSecurityUtils","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments","value":[{"text":"TSSecurityUtils","kind":"identifier"}]},{"op":"replace","value":[{"text":"TSSecurityUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle"},{"value":"Log","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments","value":[{"text":"Log","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"Log"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle"},{"value":"TSCore","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/fragments","op":"replace","value":[{"kind":"identifier","text":"TSCore"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/navigatorTitle","value":[{"kind":"identifier","text":"TSCore"}],"op":"replace"}]}]}