{"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@TSCoreSDK@objc(cs)TSSecurityUtils(im)init","modules":[{"name":"TSCoreSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/tscoresdk\/tssecurityutils\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/init"},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/init":{"url":"\/documentation\/tscoresdk\/tssecurityutils\/init","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/init"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"TSSecurityUtils","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments","op":"replace","value":[{"kind":"identifier","text":"TSSecurityUtils"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle","value":[{"text":"TSSecurityUtils","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}