{"kind":"symbol","identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomNumber(digits:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/tscoresdk\/tssecurityutils\/randomnumber(digits:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils"]]},"metadata":{"role":"symbol","externalID":"s:9TSCoreSDK15TSSecurityUtilsC12randomNumber6digitsS2i_tFZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"randomNumber","kind":"identifier"},{"kind":"text","text":"("},{"text":"digits","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"randomNumber(digits:)","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"TSCoreSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"randomNumber","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digits"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"}],"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/randomNumber(digits:)":{"abstract":[],"type":"topic","url":"\/documentation\/tscoresdk\/tssecurityutils\/randomnumber(digits:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"randomNumber","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"digits"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"randomNumber(digits:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomNumber(digits:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title","value":"TSSecurityUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments","op":"replace","value":[{"text":"TSSecurityUtils","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle","value":[{"kind":"identifier","text":"TSSecurityUtils"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}