{"abstract":[{"text":"A class defining the styles that can be applied to the parsed Markdown. The ","type":"text"},{"code":"fontName","type":"codeVoice"},{"type":"text","text":" property is optional, and if it’s not set then the "},{"type":"codeVoice","code":"fontName"},{"text":" property of the Body style will be applied.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification"]]},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/color","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontName","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontSize","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontStyle"],"anchor":"Instance-Properties"}],"metadata":{"title":"BasicStyles","modules":[{"name":"IdentityVerification"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BasicStyles","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@IdentityVerification@objc(cs)BasicStyles","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasicStyles","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"If that is not set, then the system default will be used.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/basicstyles"]},{"paths":["\/documentation\/identityverification\/basicstyles"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","doc:\/\/com.TransmitSecurity.IdentityVerification\/SH"]}],"kind":"symbol","sections":[],"references":{"doc://com.TransmitSecurity.IdentityVerification/objc(cs)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.TransmitSecurity.IdentityVerification/SH":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.TransmitSecurity.IdentityVerification/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.IdentityVerification/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/fontName":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/identityverification\/basicstyles\/fontname","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"fontName","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontName"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/fontStyle":{"url":"\/documentation\/identityverification\/basicstyles\/fontstyle","title":"fontStyle","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontStyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"kind":"text","text":": "},{"text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/color":{"url":"\/documentation\/identityverification\/basicstyles\/color","title":"color","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/color","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/init":{"title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/identityverification\/basicstyles\/init","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/init"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FontProperties","kind":"identifier"}],"navigatorTitle":[{"text":"FontProperties","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/fontproperties","kind":"symbol","title":"FontProperties"},"doc://com.TransmitSecurity.IdentityVerification/SQ":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/fontSize":{"title":"fontSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontSize"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/identityverification\/basicstyles\/fontsize","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontSize"},"doc://com.TransmitSecurity.IdentityVerification/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"BasicStyles","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"BasicStyles"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"BasicStyles","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/init"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BasicStyles"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"BasicStyles","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments","op":"replace","value":[{"text":"BasicStyles","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"BasicStyles"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle"}]}]}