{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/tsidentityverification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/identityverification\/tsidentityverification"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSIdentityVerification","kind":"identifier"}]}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/delegate","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/faceAuthDelegate","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/mosaicUIDelegate"],"title":"Type Properties","anchor":"Type-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/initialize(baseUrl:clientId:)","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/initializeSDK(configuration:)","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/recapture()","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/start(startToken:)","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startFaceAuth(deviceSessionId:)","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startMosaicUI(startToken:)"],"generated":true,"anchor":"Type-Methods"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/TSLogConfigurable-Implementations"]}],"kind":"symbol","metadata":{"modules":[{"name":"IdentityVerification"}],"externalID":"c:@M@IdentityVerification@objc(cs)TSIdentityVerification","title":"TSIdentityVerification","roleHeading":"Class","symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSIdentityVerification","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}]},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","doc:\/\/com.TransmitSecurity.IdentityVerification\/SH","doc:\/\/com.TransmitSecurity.IdentityVerification\/9TSCoreSDK17TSLogConfigurableP"],"kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification"]]},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/delegate":{"title":"delegate","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/delegate","url":"\/documentation\/identityverification\/tsidentityverification\/delegate","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Notifies of changes in verification status or errors. The status changes as the user progresses through the verification flow and once the verification checks are processed. Status updates can be used to display the relevant UI to the user, and to proceed after processing is completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSIdentityVerificationDelegate","preciseIdentifier":"s:20IdentityVerification010TSIdentityB8DelegateP"},{"kind":"text","text":"?"}]},"doc://com.TransmitSecurity.IdentityVerification/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","title":"Swift.Equatable"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/mosaicUIDelegate":{"title":"mosaicUIDelegate","kind":"symbol","url":"\/documentation\/identityverification\/tsidentityverification\/mosaicuidelegate","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/mosaicUIDelegate","type":"topic","abstract":[{"text":"Notifies of changes in verification status or errors. The status changes as the user progresses through the verification flow and once the verification checks are processed. Status updates can be used to display the relevant UI to the user, and to proceed after processing is completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mosaicUIDelegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:20IdentityVerification010TSIdentityB16MosaicUIDelegateP","text":"TSIdentityVerificationMosaicUIDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.IdentityVerification/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/startFaceAuth(deviceSessionId:)":{"url":"\/documentation\/identityverification\/tsidentityverification\/startfaceauth(devicesessionid:)","abstract":[{"type":"text","text":"Initiates the face authentication process for the user and guides them through the entire face authentication flow using the Transmit experience."}],"type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startFaceAuth(deviceSessionId:)","kind":"symbol","title":"startFaceAuth(deviceSessionId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startFaceAuth"},{"text":"(","kind":"text"},{"text":"deviceSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/faceAuthDelegate":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAuthDelegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"TSIdentityFaceAuthenticationDelegate","kind":"typeIdentifier","preciseIdentifier":"s:20IdentityVerification36TSIdentityFaceAuthenticationDelegateP"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/faceAuthDelegate","role":"symbol","kind":"symbol","url":"\/documentation\/identityverification\/tsidentityverification\/faceauthdelegate","title":"faceAuthDelegate","abstract":[{"type":"text","text":"Notifies of changes in face authentication status or errors. The status changes as the user progresses through the face authentication flow and once the authentication checks are processed. Status updates can be used to display the relevant UI to the user, and to proceed after processing is completed."}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/recapture()":{"role":"symbol","kind":"symbol","title":"recapture()","url":"\/documentation\/identityverification\/tsidentityverification\/recapture()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recapture","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Recaptures the required images in case the "},{"type":"codeVoice","code":"recapture"},{"text":" status is returned (e.g., if some data couldn’t be extracted due to poor image quality)","type":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/recapture()","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/initialize(baseUrl:clientId:)":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"abstract":[{"text":"Initializes the Identity Verification SDK,","type":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/initialize(baseUrl:clientId:)","url":"\/documentation\/identityverification\/tsidentityverification\/initialize(baseurl:clientid:)","title":"initialize(baseUrl:clientId:)"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/start(startToken:)":{"role":"symbol","kind":"symbol","title":"start(startToken:)","url":"\/documentation\/identityverification\/tsidentityverification\/start(starttoken:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"startToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initiates the verification process for the user and guides them through the entire identity verification flow using the Transmit experience."}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/start(startToken:)","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/TSLogConfigurable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/TSLogConfigurable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"TSLogConfigurable Implementations","url":"\/documentation\/identityverification\/tsidentityverification\/tslogconfigurable-implementations"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/initializeSDK(configuration:)":{"type":"topic","title":"initializeSDK(configuration:)","kind":"symbol","abstract":[{"text":"Initializes the Identity Verification SDK,","type":"text"},{"type":"text","text":" "},{"text":"Credentials are configured from TransmitSecurity.plist file","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeSDK"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"TSIdvConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:20IdentityVerification18TSIdvConfigurationV"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/initializeSDK(configuration:)","url":"\/documentation\/identityverification\/tsidentityverification\/initializesdk(configuration:)"},"doc://com.TransmitSecurity.IdentityVerification/9TSCoreSDK17TSLogConfigurableP":{"title":"TSCoreSDK.TSLogConfigurable","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/9TSCoreSDK17TSLogConfigurableP"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/startMosaicUI(startToken:)":{"title":"startMosaicUI(startToken:)","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/startMosaicUI(startToken:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startMosaicUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/identityverification\/tsidentityverification\/startmosaicui(starttoken:)","kind":"symbol","role":"symbol","abstract":[{"text":"Initiates the verification process for the user and guides them through the entire identity verification flow using the Transmit experience.","type":"text"},{"type":"text","text":" "},{"text":"This process  includes additional smart UI screens to enhance the user’s experience.","type":"text"}]},"doc://com.TransmitSecurity.IdentityVerification/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject"},"doc://com.TransmitSecurity.IdentityVerification/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject","type":"unresolvable"},"doc://com.TransmitSecurity.IdentityVerification/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SH","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"TSIdentityVerification","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"TSIdentityVerification"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TSIdentityVerification"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSIdentityVerification"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","value":"TSIdentityVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","value":[{"text":"TSIdentityVerification","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TSIdentityVerification"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle"}]}]}