{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/alignment","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/color","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontName","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontSize","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontStyle"],"generated":true}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/linestyles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/identityverification\/linestyles"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"LineStyles"}],"role":"symbol","symbolKind":"class","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LineStyles","kind":"identifier"}],"modules":[{"name":"IdentityVerification"}],"roleHeading":"Class","externalID":"c:@M@IdentityVerification@objc(cs)LineStyles"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}],"languages":["swift"]}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineProperties","doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","doc:\/\/com.TransmitSecurity.IdentityVerification\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/color":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/color","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/linestyles\/color","kind":"symbol","title":"color"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineProperties":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineProperties","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineProperties"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineProperties"}],"title":"LineProperties","url":"\/documentation\/identityverification\/lineproperties"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/fontStyle":{"role":"symbol","title":"fontStyle","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontStyle","kind":"symbol","url":"\/documentation\/identityverification\/linestyles\/fontstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO"}],"type":"topic","abstract":[]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/fontSize":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontSize","title":"fontSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontSize"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/identityverification\/linestyles\/fontsize","role":"symbol","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineStyles","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","role":"symbol","url":"\/documentation\/identityverification\/linestyles","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FontProperties","kind":"identifier"}],"navigatorTitle":[{"text":"FontProperties","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/fontproperties","kind":"symbol","title":"FontProperties"},"doc://com.TransmitSecurity.IdentityVerification/objc(cs)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/fontName":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/fontName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fontName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/linestyles\/fontname","kind":"symbol","title":"fontName"},"doc://com.TransmitSecurity.IdentityVerification/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s7CVarArgP"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/alignment":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/linestyles\/alignment","kind":"symbol","title":"alignment"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.IdentityVerification/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles/init":{"title":"init","url":"\/documentation\/identityverification\/linestyles\/init","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.IdentityVerification/SH":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SH","title":"Swift.Hashable"},"doc://com.TransmitSecurity.IdentityVerification/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"LineStyles"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"LineStyles"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"LineStyles","kind":"identifier"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles\/init"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"LineStyles","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"LineStyles","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/fragments","value":[{"text":"LineStyles","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/navigatorTitle","value":[{"kind":"identifier","text":"LineStyles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}