{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"},"relationshipsSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.AccountProtection\/s7CVarArgP","doc:\/\/com.TransmitSecurity.AccountProtection\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.AccountProtection\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.AccountProtection\/SQ","doc:\/\/com.TransmitSecurity.AccountProtection\/SH","doc:\/\/com.TransmitSecurity.AccountProtection\/9TSCoreSDK17TSLogConfigurableP"],"kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSAccountProtection","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"externalID":"c:@M@AccountProtection@objc(cs)TSAccountProtection","symbolKind":"class","modules":[{"name":"AccountProtection"}],"title":"TSAccountProtection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSAccountProtection","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"topicSections":[{"title":"Type Aliases","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/CompletionResult","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/SessionTokenCompletion"],"generated":true,"anchor":"Type-Aliases"},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/clearUser()","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/getSessionToken(completion:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:completion:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initializeSDK(userId:completion:configuration:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/setUserId(_:)","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/triggerAction(_:options:completion:)"],"generated":true},{"identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/TSLogConfigurable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection"]]},"references":{"doc://com.TransmitSecurity.AccountProtection/9TSCoreSDK17TSLogConfigurableP":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/9TSCoreSDK17TSLogConfigurableP","type":"unresolvable","title":"TSCoreSDK.TSLogConfigurable"},"doc://com.TransmitSecurity.AccountProtection/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/triggerAction(_:options:completion:)":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/triggerAction(_:options:completion:)","role":"symbol","title":"triggerAction(_:options:completion:)","url":"\/documentation\/accountprotection\/tsaccountprotection\/triggeraction(_:options:completion:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"triggerAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TSActionEventOptions","preciseIdentifier":"s:17AccountProtection20TSActionEventOptionsV"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:17AccountProtection37TransmitSecurityTriggerActionResponseV","text":"TransmitSecurityTriggerActionResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:17AccountProtection016TransmitSecurityaB5ErrorO","kind":"typeIdentifier","text":"TransmitSecurityAccountProtectionError"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Reports a user actionType event to the SDK. The different action types are predefined in the Account Protection server."}],"type":"topic"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/getSessionToken(completion:)":{"abstract":[{"text":"Returns current session token","type":"text"}],"kind":"symbol","url":"\/documentation\/accountprotection\/tsaccountprotection\/getsessiontoken(completion:)","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/getSessionToken(completion:)","role":"symbol","title":"getSessionToken(completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSessionToken"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17AccountProtection09TSAccountB0C22SessionTokenCompletiona","text":"SessionTokenCompletion","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/CompletionResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionResult"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionResult"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/CompletionResult","kind":"symbol","title":"TSAccountProtection.CompletionResult","url":"\/documentation\/accountprotection\/tsaccountprotection\/completionresult","type":"topic","abstract":[]},"doc://com.TransmitSecurity.AccountProtection/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/SQ","title":"Swift.Equatable"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/TSLogConfigurable-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/accountprotection\/tsaccountprotection\/tslogconfigurable-implementations","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/TSLogConfigurable-Implementations","role":"collectionGroup","title":"TSLogConfigurable Implementations"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/clearUser()":{"type":"topic","title":"clearUser()","abstract":[{"type":"text","text":"Clears the user context for all subsequent events in the application session"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/clearUser()","url":"\/documentation\/accountprotection\/tsaccountprotection\/clearuser()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearUser"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/SessionTokenCompletion":{"abstract":[],"kind":"symbol","url":"\/documentation\/accountprotection\/tsaccountprotection\/sessiontokencompletion","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/SessionTokenCompletion","role":"symbol","title":"TSAccountProtection.SessionTokenCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionTokenCompletion"}],"navigatorTitle":[{"text":"SessionTokenCompletion","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/initialize(baseUrl:clientId:userId:configuration:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"baseUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TSInitSDKConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV"},{"kind":"text","text":"?)"}],"url":"\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:)","type":"topic","abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:)","title":"initialize(baseUrl:clientId:userId:configuration:)","role":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/setUserId(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/setUserId(_:)","abstract":[{"type":"text","text":"Sets the user context for all subsequent events in the session (or until the user is explicitly cleared) It should be set only after you’ve fully authenticated the user (including, for example, any 2FA that was required)."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"setUserId(_:)","role":"symbol","url":"\/documentation\/accountprotection\/tsaccountprotection\/setuserid(_:)"},"doc://com.TransmitSecurity.AccountProtection/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/objc(pl)NSObject"},"doc://com.TransmitSecurity.AccountProtection/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/objc(cs)NSObject"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/initializeSDK(userId:completion:configuration:)":{"type":"topic","abstract":[{"text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Credentials are configured from TransmitSecurity.plist file"}],"url":"\/documentation\/accountprotection\/tsaccountprotection\/initializesdk(userid:completion:configuration:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeSDK"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C10Completiona"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"TSDrsConfiguration","preciseIdentifier":"s:17AccountProtection18TSDrsConfigurationV","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"initializeSDK(userId:completion:configuration:)","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initializeSDK(userId:completion:configuration:)","kind":"symbol"},"doc://com.TransmitSecurity.AccountProtection/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/SH"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/initialize(baseUrl:clientId:userId:configuration:completion:)":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:completion:)","title":"initialize(baseUrl:clientId:userId:configuration:completion:)","url":"\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:completion:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"TSInitSDKConfiguration","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C10Completiona"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"role":"symbol"},"doc://com.TransmitSecurity.AccountProtection/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/s7CVarArgP"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/Completion":{"title":"TSAccountProtection.Completion","url":"\/documentation\/accountprotection\/tsaccountprotection\/completion","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Completion"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Completion","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"TSAccountProtection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TSAccountProtection"}]},{"op":"replace","value":null,"path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.AccountProtection\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSAccountProtection","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"TSAccountProtection","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments"},{"op":"replace","value":[{"text":"TSAccountProtection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}