{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSCore"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/tscoresdk\/tscore"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tscoresdk\/tscore"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/clientPlatform"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK"]]},"metadata":{"roleHeading":"Class","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSCore"}],"externalID":"c:@M@TSCoreSDK@objc(cs)TSCore","title":"TSCore","modules":[{"name":"TSCoreSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSCore","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH"]}],"references":{"doc://com.TransmitSecurity.TSCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore/init":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/init","title":"init","url":"\/documentation\/tscoresdk\/tscore\/init","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore":{"type":"topic","title":"TSCore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSCore","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tscore","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSCore"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP"},"doc://com.TransmitSecurity.TSCoreSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH"},"doc://com.TransmitSecurity.TSCoreSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore/clientPlatform":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"clientPlatform","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/tscoresdk\/tscore\/clientplatform","type":"topic","title":"clientPlatform","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/clientPlatform","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ"},"doc://com.TransmitSecurity.TSCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"TSCore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TSCore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TSCore"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/init"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSCore"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/title","value":"TSCore"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/fragments","value":[{"kind":"identifier","text":"TSCore"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/navigatorTitle","value":[{"text":"TSCore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}