{"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/pn","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/log\/pn"]},{"paths":["\/documentation\/tscoresdk\/log\/pn"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@NSManaged"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pn","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"pn"}],"symbolKind":"property","extendedModule":"TSCoreSDK","externalID":"c:@CM@TSCoreSDK@objc(cs)Log(py)pn","modules":[{"name":"TSCoreSDK"}],"title":"pn"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log"]]},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/pn":{"navigatorTitle":[{"kind":"identifier","text":"pn"}],"title":"pn","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/pn","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tscoresdk\/log\/pn","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"pn","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pn"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"pn"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title","value":"Log"},{"value":[{"kind":"identifier","text":"Log"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Log"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1pn\/title","value":"pn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1pn\/fragments","value":[{"kind":"identifier","text":"pn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}