{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logDestination","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destination","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TSLoggerDestination","preciseIdentifier":"s:9TSCoreSDK19TSLoggerDestinationO"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/tsidentityverification\/logdestination(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/TSLogConfigurable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"TSLogConfigurable.logDestination(_:)","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/logDestination(_:)"},"metadata":{"modules":[{"name":"IdentityVerification","relatedModules":["TSCoreSDK"]}],"symbolKind":"method","role":"symbol","extendedModule":"TSCoreSDK","roleHeading":"Type Method","title":"logDestination(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logDestination"},{"kind":"text","text":"("},{"preciseIdentifier":"s:9TSCoreSDK19TSLoggerDestinationO","text":"TSLoggerDestination","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9TSCoreSDK17TSLogConfigurablePAAE14logDestinationyyAA08TSLoggerF0OFZ::SYNTHESIZED::c:@M@IdentityVerification@objc(cs)TSIdentityVerification"},"kind":"symbol","references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/logDestination(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logDestination"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9TSCoreSDK19TSLoggerDestinationO","text":"TSLoggerDestination"},{"kind":"text","text":")"}],"title":"logDestination(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/logDestination(_:)","abstract":[],"role":"symbol","url":"\/documentation\/identityverification\/tsidentityverification\/logdestination(_:)"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/TSLogConfigurable-Implementations":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/TSLogConfigurable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"TSLogConfigurable Implementations","url":"\/documentation\/identityverification\/tsidentityverification\/tslogconfigurable-implementations"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","value":"TSIdentityVerification","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","value":[{"text":"TSIdentityVerification","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TSIdentityVerification"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}