{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mosaicUIDelegate"},{"text":": ","kind":"text"},{"text":"TSIdentityVerificationMosaicUIDelegate","kind":"typeIdentifier","preciseIdentifier":"s:20IdentityVerification010TSIdentityB16MosaicUIDelegateP","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationMosaicUIDelegate"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/mosaicUIDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"]]},"abstract":[{"type":"text","text":"Notifies of changes in verification status or errors. The status changes as the user progresses through the verification flow and once the verification checks are processed. Status updates can be used to display the relevant UI to the user, and to proceed after processing is completed."}],"variants":[{"paths":["\/documentation\/identityverification\/tsidentityverification\/mosaicuidelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","externalID":"s:20IdentityVerification010TSIdentityB0C16mosaicUIDelegateAA0cb6MosaicE0_pSgvpZ","modules":[{"name":"IdentityVerification"}],"title":"mosaicUIDelegate","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mosaicUIDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20IdentityVerification010TSIdentityB16MosaicUIDelegateP","text":"TSIdentityVerificationMosaicUIDelegate"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Type Property"},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerificationMosaicUIDelegate":{"abstract":[],"kind":"symbol","type":"topic","title":"TSIdentityVerificationMosaicUIDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TSIdentityVerificationMosaicUIDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TSIdentityVerificationMosaicUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationMosaicUIDelegate","url":"\/documentation\/identityverification\/tsidentityverificationmosaicuidelegate"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/mosaicUIDelegate":{"title":"mosaicUIDelegate","kind":"symbol","url":"\/documentation\/identityverification\/tsidentityverification\/mosaicuidelegate","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/mosaicUIDelegate","type":"topic","abstract":[{"text":"Notifies of changes in verification status or errors. The status changes as the user progresses through the verification flow and once the verification checks are processed. Status updates can be used to display the relevant UI to the user, and to proceed after processing is completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mosaicUIDelegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:20IdentityVerification010TSIdentityB16MosaicUIDelegateP","text":"TSIdentityVerificationMosaicUIDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","op":"replace","value":"TSIdentityVerification"},{"op":"replace","value":[{"kind":"identifier","text":"TSIdentityVerification"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","op":"replace","value":[{"text":"TSIdentityVerification","kind":"identifier"}]}]}]}