{"metadata":{"modules":[{"name":"IdentityVerification"}],"title":"TSLogConfigurable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/TSLogConfigurable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/tsidentityverification\/tslogconfigurable-implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/logDestination(_:)","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/setLogLevel(_:)"],"anchor":"Type-Methods","generated":true}],"kind":"article","references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/setLogLevel(_:)":{"url":"\/documentation\/identityverification\/tsidentityverification\/setloglevel(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLogLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TSLogLevel","preciseIdentifier":"s:9TSCoreSDK10TSLogLevelO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/setLogLevel(_:)","title":"setLogLevel(_:)","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification/logDestination(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logDestination"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9TSCoreSDK19TSLoggerDestinationO","text":"TSLoggerDestination"},{"kind":"text","text":")"}],"title":"logDestination(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification\/logDestination(_:)","abstract":[],"role":"symbol","url":"\/documentation\/identityverification\/tsidentityverification\/logdestination(_:)"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSIdentityVerification","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","op":"replace","value":[{"text":"TSIdentityVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","value":[{"text":"TSIdentityVerification","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}