{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/color","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontName","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontSize","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontStyle"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification"]]},"metadata":{"navigatorTitle":[{"text":"FontProperties","kind":"identifier"}],"modules":[{"name":"IdentityVerification"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FontProperties"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"FontProperties","role":"symbol","externalID":"s:20IdentityVerification14FontPropertiesP"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FontProperties"}]}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityverification\/fontproperties"]}],"kind":"symbol","sections":[],"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineStyles","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","role":"symbol","url":"\/documentation\/identityverification\/linestyles","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties/color":{"type":"topic","role":"symbol","kind":"symbol","required":true,"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/color","url":"\/documentation\/identityverification\/fontproperties\/color","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"color"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties/fontSize":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontSize","type":"topic","url":"\/documentation\/identityverification\/fontproperties\/fontsize","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontSize"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"title":"fontSize","role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties/fontStyle":{"type":"topic","role":"symbol","kind":"symbol","required":true,"abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontStyle","url":"\/documentation\/identityverification\/fontproperties\/fontstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO"}],"title":"fontStyle"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FontProperties","kind":"identifier"}],"navigatorTitle":[{"text":"FontProperties","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/fontproperties","kind":"symbol","title":"FontProperties"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties/fontName":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties\/fontName","type":"topic","url":"\/documentation\/identityverification\/fontproperties\/fontname","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"title":"fontName","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/title","op":"replace","value":"LineStyles"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/fragments","value":[{"kind":"identifier","text":"LineStyles"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/navigatorTitle","value":[{"kind":"identifier","text":"LineStyles"}]},{"value":"BasicStyles","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments","value":[{"text":"BasicStyles","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"BasicStyles"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle"}]}]}