{"metadata":{"title":"color","symbolKind":"property","modules":[{"name":"IdentityVerification"}],"externalID":"s:20IdentityVerification11BasicStylesC5colorSo7UIColorCvp","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/color","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"FontProperties.color","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles"]]},"variants":[{"paths":["\/documentation\/identityverification\/basicstyles\/color"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/color":{"url":"\/documentation\/identityverification\/basicstyles\/color","title":"color","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/color","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title","value":"BasicStyles"},{"value":[{"text":"BasicStyles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle","op":"replace","value":[{"text":"BasicStyles","kind":"identifier"}]}]}]}