{"metadata":{"symbolKind":"property","externalID":"s:20IdentityVerification11BasicStylesC9fontStyleAA04FontF0Ovp","modules":[{"name":"IdentityVerification"}],"role":"symbol","roleHeading":"Instance Property","title":"fontStyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"text":": ","kind":"text"},{"text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontStyle"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fontStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FontStyle","kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/identityverification\/basicstyles\/fontstyle"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"FontProperties.fontStyle","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles"]]},"references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles/fontStyle":{"url":"\/documentation\/identityverification\/basicstyles\/fontstyle","title":"fontStyle","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles\/fontStyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontStyle"},{"kind":"text","text":": "},{"text":"FontStyle","preciseIdentifier":"s:20IdentityVerification9FontStyleO","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontStyle":{"url":"\/documentation\/identityverification\/fontstyle","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FontStyle","kind":"identifier"}],"kind":"symbol","title":"FontStyle","abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","navigatorTitle":[{"kind":"identifier","text":"FontStyle"}]}},"variantOverrides":[{"patch":[{"value":"BasicStyles","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments","op":"replace","value":[{"kind":"identifier","text":"BasicStyles"}]},{"value":[{"text":"BasicStyles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}