{"variants":[{"paths":["\/documentation\/identityverification"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/identityverification"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[[]]},"topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/MarkdownLineProcessor","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/MarkdownTokeniser","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"],"generated":true,"title":"Classes"},{"anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/CharacterStyling","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineProperties","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyling","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityFaceAuthenticationDelegate","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationDelegate","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationMosaicUIDelegate"],"title":"Protocols"},{"anchor":"Structures","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/CharacterRule","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineRule","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/SwiftyLine","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdvConfiguration","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Token"],"generated":true,"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Cancel","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/ChangeApplication","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Remove","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/SpaceAllowed","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationError","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSRecaptureReason","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TokenType"],"anchor":"Enumerations","generated":true},{"title":"Extended Modules","generated":true,"anchor":"Extended-Modules","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSCoreSDK"]}],"sections":[],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","interfaceLanguage":"swift"},"metadata":{"externalID":"IdentityVerification","roleHeading":"Framework","role":"collection","title":"IdentityVerification","symbolKind":"module","modules":[{"name":"IdentityVerification"}]},"primaryContentSections":[{"content":[{"type":"heading","text":"Introduction","level":2,"anchor":"Introduction"},{"inlineContent":[{"type":"text","text":"The Identity Verification SDK is an iOS client SDK that allows you to quickly integrate identity verification into your iOS application. This lets you securely verify the identity of your customers using documents like their driver’s license or passport. Learn more about our "},{"type":"reference","identifier":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/identity_verification_overview\/","isActive":true},{"text":" or check out the ","type":"text"},{"identifier":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/quick_start_ios\/","type":"reference","isActive":true},{"type":"text","text":".The entry point to the SDK API is set as the "},{"type":"codeVoice","code":"TSIdentityVerification"},{"type":"text","text":" class."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","references":{"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerificationDelegate":{"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationDelegate","abstract":[],"navigatorTitle":[{"text":"TSIdentityVerificationDelegate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TSIdentityVerificationDelegate","kind":"identifier"}],"title":"TSIdentityVerificationDelegate","url":"\/documentation\/identityverification\/tsidentityverificationdelegate","kind":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyles":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LineStyles","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","role":"symbol","url":"\/documentation\/identityverification\/linestyles","title":"LineStyles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyles"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/Token":{"navigatorTitle":[{"text":"Token","kind":"identifier"}],"title":"Token","kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Token","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Token","kind":"identifier"}],"url":"\/documentation\/identityverification\/token"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontProperties":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontProperties","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FontProperties","kind":"identifier"}],"navigatorTitle":[{"text":"FontProperties","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/identityverification\/fontproperties","kind":"symbol","title":"FontProperties"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSRecaptureReason":{"role":"symbol","navigatorTitle":[{"text":"TSRecaptureReason","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TSRecaptureReason","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSRecaptureReason","title":"TSRecaptureReason","url":"\/documentation\/identityverification\/tsrecapturereason"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerificationError":{"role":"symbol","title":"TSIdentityVerificationError","abstract":[{"type":"text","text":"List of possible SDK errors"}],"kind":"symbol","type":"topic","url":"\/documentation\/identityverification\/tsidentityverificationerror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TSIdentityVerificationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerificationError"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationError"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdvConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSIdvConfiguration"}],"abstract":[{"text":"Additional configuration for SDK initialization.","type":"text"}],"url":"\/documentation\/identityverification\/tsidvconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdvConfiguration","title":"TSIdvConfiguration","navigatorTitle":[{"text":"TSIdvConfiguration","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdentityVerification"}],"abstract":[],"type":"topic","url":"\/documentation\/identityverification\/tsidentityverification","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification","navigatorTitle":[{"kind":"identifier","text":"TSIdentityVerification"}],"kind":"symbol","title":"TSIdentityVerification"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityVerificationMosaicUIDelegate":{"abstract":[],"kind":"symbol","type":"topic","title":"TSIdentityVerificationMosaicUIDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TSIdentityVerificationMosaicUIDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TSIdentityVerificationMosaicUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerificationMosaicUIDelegate","url":"\/documentation\/identityverification\/tsidentityverificationmosaicuidelegate"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineStyling":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyling","role":"symbol","abstract":[],"url":"\/documentation\/identityverification\/linestyling","title":"LineStyling","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStyling"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineStyling"}],"kind":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/IdentityVerificationVersionString":{"kind":"symbol","url":"\/documentation\/identityverification\/identityverificationversionstring","abstract":[{"type":"text","text":"Project version string for IdentityVerification."}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/IdentityVerificationVersionString","type":"topic","title":"IdentityVerificationVersionString","fragments":[{"kind":"identifier","text":"IdentityVerificationVersionString"}],"role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/CharacterRule":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CharacterRule","kind":"identifier"}],"navigatorTitle":[{"text":"CharacterRule","kind":"identifier"}],"type":"topic","url":"\/documentation\/identityverification\/characterrule","title":"CharacterRule","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/CharacterRule","abstract":[],"kind":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSIdentityFaceAuthenticationDelegate":{"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityFaceAuthenticationDelegate","role":"symbol","abstract":[],"url":"\/documentation\/identityverification\/tsidentityfaceauthenticationdelegate","title":"TSIdentityFaceAuthenticationDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSIdentityFaceAuthenticationDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSIdentityFaceAuthenticationDelegate"}],"kind":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/IdentityVerificationVersionNumber":{"abstract":[{"type":"text","text":"Project version number for IdentityVerification."}],"kind":"symbol","title":"IdentityVerificationVersionNumber","type":"topic","fragments":[{"kind":"identifier","text":"IdentityVerificationVersionNumber"}],"url":"\/documentation\/identityverification\/identityverificationversionnumber","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/IdentityVerificationVersionNumber","role":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/MarkdownLineProcessor":{"url":"\/documentation\/identityverification\/markdownlineprocessor","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MarkdownLineProcessor","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MarkdownLineProcessor"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/MarkdownLineProcessor","title":"MarkdownLineProcessor"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TSCoreSDK":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSCoreSDK","abstract":[],"url":"\/documentation\/identityverification\/tscoresdk","title":"TSCoreSDK","role":"collection","type":"topic"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/FontStyle":{"url":"\/documentation\/identityverification\/fontstyle","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FontStyle","kind":"identifier"}],"kind":"symbol","title":"FontStyle","abstract":[],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/FontStyle","navigatorTitle":[{"kind":"identifier","text":"FontStyle"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/MarkdownTokeniser":{"kind":"symbol","url":"\/documentation\/identityverification\/markdowntokeniser","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/MarkdownTokeniser","role":"symbol","navigatorTitle":[{"text":"MarkdownTokeniser","kind":"identifier"}],"abstract":[],"title":"MarkdownTokeniser","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MarkdownTokeniser","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/BasicStyles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicStyles","kind":"identifier"}],"abstract":[{"type":"text","text":"A class defining the styles that can be applied to the parsed Markdown. The "},{"type":"codeVoice","code":"fontName"},{"text":" property is optional, and if it’s not set then the ","type":"text"},{"type":"codeVoice","code":"fontName"},{"type":"text","text":" property of the Body style will be applied."}],"type":"topic","url":"\/documentation\/identityverification\/basicstyles","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","navigatorTitle":[{"kind":"identifier","text":"BasicStyles"}],"kind":"symbol","title":"BasicStyles"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/ChangeApplication":{"url":"\/documentation\/identityverification\/changeapplication","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/ChangeApplication","type":"topic","title":"ChangeApplication","role":"symbol","navigatorTitle":[{"text":"ChangeApplication","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChangeApplication"}],"abstract":[],"kind":"symbol"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/SwiftyLine":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SwiftyLine"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/SwiftyLine","url":"\/documentation\/identityverification\/swiftyline","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SwiftyLine","kind":"identifier"}],"abstract":[],"type":"topic","title":"SwiftyLine"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineProperties":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineProperties","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineProperties"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineProperties"}],"title":"LineProperties","url":"\/documentation\/identityverification\/lineproperties"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/Remove":{"url":"\/documentation\/identityverification\/remove","kind":"symbol","abstract":[],"title":"Remove","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Remove","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Remove"}],"type":"topic","navigatorTitle":[{"text":"Remove","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/Cancel":{"navigatorTitle":[{"kind":"identifier","text":"Cancel"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/Cancel","title":"Cancel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Cancel","kind":"identifier"}],"url":"\/documentation\/identityverification\/cancel","role":"symbol"},"https://developer.transmitsecurity.com/guides/verify/identity_verification_overview/":{"identifier":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/identity_verification_overview\/","type":"link","titleInlineContent":[{"type":"text","text":"identity verification services"}],"title":"identity verification services","url":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/identity_verification_overview\/"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/TokenType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TokenType","kind":"identifier"}],"type":"topic","url":"\/documentation\/identityverification\/tokentype","kind":"symbol","title":"TokenType","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TokenType","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TokenType"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/LineRule":{"url":"\/documentation\/identityverification\/linerule","kind":"symbol","abstract":[],"title":"LineRule","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineRule","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LineRule","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineRule"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/CharacterStyling":{"title":"CharacterStyling","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/CharacterStyling","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CharacterStyling"}],"url":"\/documentation\/identityverification\/characterstyling","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"CharacterStyling","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification":{"type":"topic","url":"\/documentation\/identityverification","title":"IdentityVerification","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification","role":"collection"},"doc://com.TransmitSecurity.IdentityVerification/documentation/IdentityVerification/SpaceAllowed":{"url":"\/documentation\/identityverification\/spaceallowed","navigatorTitle":[{"kind":"identifier","text":"SpaceAllowed"}],"type":"topic","title":"SpaceAllowed","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/SpaceAllowed","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpaceAllowed"}]},"https://developer.transmitsecurity.com/guides/verify/quick_start_ios/":{"identifier":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/quick_start_ios\/","type":"link","titleInlineContent":[{"type":"text","text":"quick start guide"}],"title":"quick start guide","url":"https:\/\/developer.transmitsecurity.com\/guides\/verify\/quick_start_ios\/"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/BasicStyles","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/LineStyles","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/TSIdentityVerification"],"title":"Classes"},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/IdentityVerificationVersionNumber","doc:\/\/com.TransmitSecurity.IdentityVerification\/documentation\/IdentityVerification\/IdentityVerificationVersionString"],"generated":true,"anchor":"Variables","title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/title","value":"LineStyles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/fragments","value":[{"kind":"identifier","text":"LineStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1LineStyles\/navigatorTitle","value":[{"kind":"identifier","text":"LineStyles"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/title","value":"TSIdentityVerification","op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/fragments","value":[{"kind":"identifier","text":"TSIdentityVerification"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1TSIdentityVerification\/navigatorTitle","op":"replace","value":[{"text":"TSIdentityVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/title","value":"BasicStyles"},{"value":[{"kind":"identifier","text":"BasicStyles"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.IdentityVerification~1documentation~1IdentityVerification~1BasicStyles\/navigatorTitle","value":[{"text":"BasicStyles","kind":"identifier"}]}]}]}