{"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore"]]},"metadata":{"extendedModule":"TSCoreSDK","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"clientPlatform","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"clientPlatform","modules":[{"name":"TSCoreSDK"}],"externalID":"s:9TSCoreSDK0A0C14clientPlatformSSvpZ","symbolKind":"property","roleHeading":"Type Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/clientPlatform"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientPlatform"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/tscoresdk\/tscore\/clientplatform"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore":{"type":"topic","title":"TSCore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSCore","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tscore","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSCore"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore/clientPlatform":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"clientPlatform","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/tscoresdk\/tscore\/clientplatform","type":"topic","title":"clientPlatform","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/clientPlatform","abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSCore","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/title"},{"value":[{"text":"TSCore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TSCore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}