{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/tscoresdk\/tscore\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/init"},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"TSCoreSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","externalID":"c:@M@TSCoreSDK@objc(cs)TSCore(im)init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore":{"type":"topic","title":"TSCore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSCore","kind":"identifier"}],"url":"\/documentation\/tscoresdk\/tscore","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TSCore"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSCore/init":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSCore\/init","title":"init","url":"\/documentation\/tscoresdk\/tscore\/init","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"TSCore","op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/fragments","op":"replace","value":[{"kind":"identifier","text":"TSCore"}]},{"value":[{"kind":"identifier","text":"TSCore"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSCore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}