{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Log","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/log"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tscoresdk\/log"]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@TSCoreSDK@objc(cs)Log","modules":[{"name":"TSCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Log"}],"role":"symbol","title":"Log","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Log","kind":"identifier"}]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/cn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/mn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/pn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/s","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/ssn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/t","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/timestamp"]},{"generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/fetchRequest()"],"title":"Type Methods","anchor":"Type-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSManagedObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/7Combine16ObservableObjectP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSFetchRequestResult","doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK"]]},"references":{"doc://com.TransmitSecurity.TSCoreSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.TransmitSecurity.TSCoreSDK/SH":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.TransmitSecurity.TSCoreSDK/7Combine16ObservableObjectP":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/7Combine16ObservableObjectP","type":"unresolvable","title":"Combine.ObservableObject"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/s":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"s"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int16","preciseIdentifier":"s:s5Int16V"}],"navigatorTitle":[{"kind":"identifier","text":"s"}],"role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/s","type":"topic","url":"\/documentation\/tscoresdk\/log\/s","title":"s","abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log":{"url":"\/documentation\/tscoresdk\/log","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"abstract":[],"title":"Log","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSCoreSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ","type":"unresolvable"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/pn":{"navigatorTitle":[{"kind":"identifier","text":"pn"}],"title":"pn","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/pn","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/tscoresdk\/log\/pn","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.TransmitSecurity.TSCoreSDK/objc(pl)NSFetchRequestResult":{"title":"CoreData.NSFetchRequestResult","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSFetchRequestResult","type":"unresolvable"},"doc://com.TransmitSecurity.TSCoreSDK/objc(cs)NSManagedObject":{"title":"NSManagedObject","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSManagedObject","type":"unresolvable"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/mn":{"kind":"symbol","navigatorTitle":[{"text":"mn","kind":"identifier"}],"abstract":[],"title":"mn","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/mn","type":"topic","url":"\/documentation\/tscoresdk\/log\/mn","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mn"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.TransmitSecurity.TSCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/cn":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/cn","type":"topic","title":"cn","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cn","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/tscoresdk\/log\/cn","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cn"}],"abstract":[]},"doc://com.TransmitSecurity.TSCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/timestamp":{"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"url":"\/documentation\/tscoresdk\/log\/timestamp","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/timestamp","title":"timestamp","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/ssn":{"role":"symbol","kind":"symbol","title":"ssn","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/ssn","url":"\/documentation\/tscoresdk\/log\/ssn","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ssn","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ssn"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/fetchRequest()":{"type":"topic","url":"\/documentation\/tscoresdk\/log\/fetchrequest()","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchRequest"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSFetchRequest","preciseIdentifier":"c:objc(cs)NSFetchRequest"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TSCoreSDK@objc(cs)Log","text":"Log"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/fetchRequest()","title":"fetchRequest()","role":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/t":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/t","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"t","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"t","kind":"identifier"}],"title":"t","kind":"symbol","url":"\/documentation\/tscoresdk\/log\/t","type":"topic"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/Log/initWithEntity:insertIntoManagedObjectContext:":{"title":"initWithEntity:insertIntoManagedObjectContext:","role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEntity:insertIntoManagedObjectContext:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/initWithEntity:insertIntoManagedObjectContext:","url":"\/documentation\/tscoresdk\/log\/initwithentity:insertintomanagedobjectcontext:","navigatorTitle":[{"kind":"identifier","text":"initWithEntity:insertIntoManagedObjectContext:"}]},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"Log","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"Log"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Log"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/cn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/mn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/pn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/s","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/ssn","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/t","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/timestamp"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/Log\/initWithEntity:insertIntoManagedObjectContext:"],"title":"Instance Methods","generated":true}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSManagedObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Log"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSManagedObject","text":"NSManagedObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1s\/title","value":"s"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1s\/fragments","op":"replace","value":[{"text":"s","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/title","op":"replace","value":"Log"},{"value":[{"text":"Log","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/fragments"},{"value":[{"kind":"identifier","text":"Log"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1pn\/title","value":"pn"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1pn\/fragments","value":[{"kind":"identifier","text":"pn"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1mn\/title","value":"mn"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1mn\/fragments","value":[{"text":"mn","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1cn\/title","value":"cn"},{"value":[{"kind":"identifier","text":"cn"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1cn\/fragments"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}],"op":"replace"},{"op":"replace","value":"ssn","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1ssn\/title"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1ssn\/fragments","value":[{"kind":"identifier","text":"ssn"}],"op":"replace"},{"op":"replace","value":"t","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1t\/title"},{"op":"replace","value":[{"text":"t","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1Log~1t\/fragments"}]}]}