{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ","doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH"],"type":"conformsTo"}],"metadata":{"modules":[{"name":"TSCoreSDK"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@TSCoreSDK@objc(cs)TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TSSecurityUtils","kind":"identifier"}],"title":"TSSecurityUtils","symbolKind":"class"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSSecurityUtils","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tscoresdk\/tssecurityutils"]},{"paths":["\/documentation\/tscoresdk\/tssecurityutils"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK"]]},"topicSections":[{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/challengeCode(verifier:)","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomBase64EncodedString(length:)","doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomNumber(digits:)"],"anchor":"Type-Methods"}],"references":{"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/init":{"url":"\/documentation\/tscoresdk\/tssecurityutils\/init","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/init"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/challengeCode(verifier:)":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/challengeCode(verifier:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"verifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"title":"challengeCode(verifier:)","url":"\/documentation\/tscoresdk\/tssecurityutils\/challengecode(verifier:)"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK":{"url":"\/documentation\/tscoresdk","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK","abstract":[],"role":"collection","type":"topic","title":"TSCoreSDK","kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.TransmitSecurity.TSCoreSDK/SH":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.TransmitSecurity.TSCoreSDK/s7CVarArgP":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/randomNumber(digits:)":{"abstract":[],"type":"topic","url":"\/documentation\/tscoresdk\/tssecurityutils\/randomnumber(digits:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"randomNumber","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"digits"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"randomNumber(digits:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomNumber(digits:)"},"doc://com.TransmitSecurity.TSCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.TransmitSecurity.TSCoreSDK/SQ":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.TransmitSecurity.TSCoreSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils":{"url":"\/documentation\/tscoresdk\/tssecurityutils","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSSecurityUtils"}],"title":"TSSecurityUtils","navigatorTitle":[{"text":"TSSecurityUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.TransmitSecurity.TSCoreSDK/documentation/TSCoreSDK/TSSecurityUtils/randomBase64EncodedString(length:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"randomBase64EncodedString","kind":"identifier"},{"kind":"text","text":"("},{"text":"length","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/randomBase64EncodedString(length:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/tscoresdk\/tssecurityutils\/randombase64encodedstring(length:)","title":"randomBase64EncodedString(length:)"},"doc://com.TransmitSecurity.TSCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.TransmitSecurity.TSCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TSSecurityUtils"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"TSSecurityUtils","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"TSSecurityUtils","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/documentation\/TSCoreSDK\/TSSecurityUtils\/init"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.TransmitSecurity.TSCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSSecurityUtils"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"TSSecurityUtils","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TSSecurityUtils"}],"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.TSCoreSDK~1documentation~1TSCoreSDK~1TSSecurityUtils\/navigatorTitle","value":[{"text":"TSSecurityUtils","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}