{"kind":"symbol","variants":[{"paths":["\/documentation\/accountprotection\/tsaccountprotection\/completion"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"AccountProtection"}],"externalID":"s:17AccountProtection09TSAccountB0C10Completiona","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Completion","kind":"identifier"}],"title":"TSAccountProtection.Completion","navigatorTitle":[{"kind":"identifier","text":"Completion"}],"role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Completion","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"CompletionResult","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C16CompletionResulta","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/CompletionResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"]]},"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"type":"topic","abstract":[],"role":"collection","title":"AccountProtection","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","kind":"symbol","url":"\/documentation\/accountprotection"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/CompletionResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionResult"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionResult"}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/CompletionResult","kind":"symbol","title":"TSAccountProtection.CompletionResult","url":"\/documentation\/accountprotection\/tsaccountprotection\/completionresult","type":"topic","abstract":[]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/Completion":{"title":"TSAccountProtection.Completion","url":"\/documentation\/accountprotection\/tsaccountprotection\/completion","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Completion"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Completion","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"TSAccountProtection","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title"},{"value":[{"text":"TSAccountProtection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle","value":[{"text":"TSAccountProtection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}