{"metadata":{"modules":[{"name":"AccountProtection"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV","text":"TSInitSDKConfiguration"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C10Completiona"},{"kind":"text","text":")"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:17AccountProtection09TSAccountB0C10initialize7baseUrl8clientId04userH013configuration10completionySS_S2SSgAA22TSInitSDKConfigurationVSgys6ResultOyytAA0cB5ErrorOGctFZ","title":"initialize(baseUrl:clientId:userId:configuration:completion:)"},"identifier":{"url":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"baseUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"https:\/\/collect.riskid.security\/device\/\", ","kind":"text"},{"kind":"externalParam","text":"clientId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","text":"TSInitSDKConfiguration","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Completion","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion","preciseIdentifier":"s:17AccountProtection09TSAccountB0C10Completiona"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"baseUrl","content":[{"inlineContent":[{"type":"text","text":"Is your Account Protection server URL (default: “https:\/\/api.transmitsecurity.io”)"}],"type":"paragraph"}]},{"name":"clientId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Is your AccountProtection client identifier."}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Is an opaque identifier of the user in your system."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Is a callback that is executed when the SDK finishes its initialization"}]}]}],"kind":"parameters"}],"sections":[],"abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:completion:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/initialize(baseUrl:clientId:userId:configuration:completion:)":{"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/initialize(baseUrl:clientId:userId:configuration:completion:)","title":"initialize(baseUrl:clientId:userId:configuration:completion:)","url":"\/documentation\/accountprotection\/tsaccountprotection\/initialize(baseurl:clientid:userid:configuration:completion:)","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseUrl"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"TSInitSDKConfiguration","preciseIdentifier":"s:17AccountProtection22TSInitSDKConfigurationV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:17AccountProtection09TSAccountB0C10Completiona"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes the AccountProtection SDK, which starts automatically tracking and submitting info of the user journey."}],"role":"symbol"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection":{"title":"TSAccountProtection","url":"\/documentation\/accountprotection\/tsaccountprotection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSAccountProtection"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSAccountProtection"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSInitSDKConfiguration":{"navigatorTitle":[{"text":"TSInitSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/accountprotection\/tsinitsdkconfiguration","abstract":[{"type":"text","text":"Configuration options object used in SDK initialization."}],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSInitSDKConfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TSInitSDKConfiguration","kind":"identifier"}],"title":"TSInitSDKConfiguration"},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection/TSAccountProtection/Completion":{"title":"TSAccountProtection.Completion","url":"\/documentation\/accountprotection\/tsaccountprotection\/completion","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Completion"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection\/TSAccountProtection\/Completion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Completion","kind":"identifier"}]},"doc://com.TransmitSecurity.AccountProtection/documentation/AccountProtection":{"title":"AccountProtection","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.TransmitSecurity.AccountProtection\/documentation\/AccountProtection","url":"\/documentation\/accountprotection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/title","value":"TSAccountProtection"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/fragments","value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.TransmitSecurity.AccountProtection~1documentation~1AccountProtection~1TSAccountProtection\/navigatorTitle","value":[{"text":"TSAccountProtection","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}